use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize)]
/// An OpenAI-compatible chat completion request.
pub struct ChatCompletionRequest {
    /// Logical model or category requested by the client.
    pub model: String,
    /// Conversation messages sent to the model.
    pub messages: Vec<ChatMessage>,

    #[serde(default)]
    /// Optional sampling temperature.
    pub temperature: Option<f32>,

    #[serde(default)]
    /// Optional maximum number of tokens to generate.
    pub max_tokens: Option<u32>,

    #[serde(default)]
    /// Whether the client requested a streaming response.
    pub stream: Option<bool>,
}

#[derive(Debug, Deserialize, Serialize)]
/// A single role/content pair in a chat conversation.
pub struct ChatMessage {
    /// Message author, such as `system`, `user`, or `assistant`.
    pub role: String,
    /// Text of the message.
    pub content: String,
}

#[derive(Debug, Serialize)]
/// An OpenAI-compatible chat completion response.
pub struct ChatCompletionResponse {
    /// Unique identifier assigned to the completion.
    pub id: String,
    /// OpenAI-compatible response object name.
    pub object: String,
    /// Model name supplied in the original client request.
    pub model: String,
    /// Completion alternatives returned by the provider.
    pub choices: Vec<Choice>,
}

#[derive(Debug, Serialize)]
/// One completion alternative in a chat completion response.
pub struct Choice {
    /// Zero-based position of this choice.
    pub index: u32,
    /// Assistant message generated by the provider.
    pub message: ChatMessage,
    /// Reason generation stopped, for example `stop`.
    pub finish_reason: String,
}
